### PR TITLE
Support powershell core

### PR DESCRIPTION
**Pull request by mrhockeymonkey**
Adding support for use on powershell core by detecting the PSEdition and correcting parameter sets as required. See [updates to invoke-restmethod](https://get-powershellblog.blogspot.co.uk/2017/11/powershell-core-web-cmdlets-in-depth.html#L08) for details. 

Also because i am using RabbitMQ 3.7 I included the quick fix described in issue https://github.com/RamblingCookieMonster/RabbitMQTools/issues/33. I'm happy to take this out or make better if we think this isn't a good enough solution. 

Feedback welcome. 

Note this was tested on powershell 6.0.2

### CODE REVIEW

**Comment by RamblingCookieMonster** [comment]
Hiyo!

Will poke around more when I get home Thursday, but at a first glance - just in case anyone is running RabbitMQ earlier 3.7, it might be worth considering support for both.

Not sure what the best route would be.  Could do something generic like `-RabbitMqVersion` to allow making other changes to the call based on version, or just a `-UseRequeue` switch, and document that folks need that if using older than 3.7.

I'd prefer using the newer behavior by default -  I'm personally of the opinion that folks should be pinning versions, and if we do a major version bump of the module, they'll refactor their code before using the newest version.  If they don't?  /me shrugs.

Cheers!

**Comment by mrhockeymonkey** [comment]
Thursday is good. I just happened to spot a few issues so gives me time to work through them as well as check it supports 3.6.

**Comment by mrhockeymonkey** [comment]
I've taken the light touch option and just optioned out lines that are incompatible with pscore. Not the neatest solution but keeps the expected behavior for people already using the module. This is now tested using both powershell 5.1 and 6.0.2 to interact with rabbitmq 3.6 and 3.7 using Get-RabbitMQOverview, Add-RabbitMQExchange, Add-RabbitMQQueue, Add-RabbitMQQueueBinding, Add-RabbitMQMessage & Get-RabbitMQMessage. But it looks like all functions use the same proxy Invoke-RestMethod. 

One thing I have omitted is adding tags to psd1 to signify core support. The only way to do this is to raise the minimum version supported up to 5.1 as per [Microsoft documentation](https://docs.microsoft.com/en-us/powershell/gallery/psget/module/modulewithpseditionsupport). Let me know if you'd like me to do so.

**Comment by mrhockeymonkey** [comment]
Gentle bump on this one. Did you manage to take a look?

**Comment by RamblingCookieMonster** [comment]
Eek!  Nope, do ping me if I'm slow - looks good to me, thanks!!

**Pull request merged**
