### PR TITLE
Moved func to /Public and ScriptsToProcess to Private

### PR DESCRIPTION
**Pull request by gaelcolas**
There was an issue with the Invoke-RestMethod proxy not working over Scheduled Tasks (or test-kitchen)[https://github.com/mariuszwojcik/RabbitMQTools/issues/4], so I moved the 2 scripts previously in ScriptsToProcess to Private functions.
This is where they should be as, AFAIK, they're meant to be used internally in the module, not in the caller's session (while it's the case of the TabExtension).

While at it, I moved the ps1 functions off the root directory to public and pulled some changes from @AtomicBlom.

Any feedback welcome.

### CODE REVIEW

**Comment by AtomicBlom** [comment]
Heh, I'd completely forgotten I'd done these changes.

**Comment by gaelcolas** [comment]
Just added a few aliases in that PR to support piping the _RabbitMQ definition export_ to the RabbitMQTools commands like so:

``` powershell
 $RabbitMQConfiguration = Get-Content -Raw rabbit_WIN-0PND6Q2OUEJ_2016-8-2.json | convertFrom-Json
    switch (($RabbitMQConfiguration | Get-Member -MemberType NoteProperty | sort-object -Descending).Name) {
        "queues" { $RabbitMQConfiguration.queues | Add-RabbitMQQueue  }
        "exchanges" { $RabbitMQConfiguration.exchanges | Add-RabbitMQExchange }
        "bindings" { $RabbitMQConfiguration.bindings | Add-RabbitMQQueueBinding }
        Default {}
    }
```

**Comment by gaelcolas** [comment]
What about that PR @RamblingCookieMonster and @gpduck? :)

**Comment by RamblingCookieMonster** [comment]
Awesome, thanks for the PR!

I don't see any issues, we can roll back if things go sideways : )  Apologies for the delay!  Need to add some scaffolding to simplify these deployments, should have this in the gallery in the next few days.

Cheers!

**Pull request merged**
